symbols:
 - "LTCBTC"
 - "BTCUSDT"
 - "EOSUSDT"
 - "ETHUSDT"
 - "XRPUSDT"
 - "BNBUSDT"
 - "TRXUSDT"
max_workers: 20

# лучше добавлять в исключения gitignore локальные конфиги, а для примера создавать config.example.yaml - когда работаешь в команде - каждый может случайно запушить в репо свою конфигу